apiVersion: v2
name: bn-kafka
description: BN Project Helm Charts
type: application

# Helm chart version
version: 1.0.2

# BN Project version
appVersion: "0.0.1"

dependencies:
  - name: kafka
    version: 31.1.0
    repository: https://charts.bitnami.com/bitnami
  - name: zookeeper
    version: 13.7.0
