global:
  projectName: bn-kafka
  appVersion: 0.0.1

zookeeper:
  replicaCount: 1
  fullnameOverride: zookeeper
  service:
    name: zookeeper
  persistence:
    enabled: true
    size: 8Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m

kafka:
  replicaCount: 1
  fullnameOverride: kafka

  service:
    name: kafka

  extraEnvVars:
    - name: KAFKA_CFG_LISTENERS
      value: PLAINTEXT://:9092
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka.bn-project.svc.cluster.local:9092
    - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
      value: PLAINTEXT:PLAINTEXT
    - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
      value: PLAINTEXT

  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m