global:
  projectName: bn-kafka
  appVersion: 0.0.1
# values.yaml

# Zookeeper configuration
zookeeper:
  enabled: true
  image:
    repository: wurstmeister/zookeeper
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  fullname: "zookeeper"
  nameOverride: "zookeeper"
  fullnameOverride: "zookeeper"
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  service:
    type: ClusterIP
    port: 2181

# Kafka configuration
kafka:
  enabled: true
  image:
    repository: wurstmeister/kafka
    tag: latest
    pullPolicy: IfNotPresent
  
  replicaCount: 1
  fullname: "kafka"
  nameOverride: "kafka"
  fullnameOverride: "kafka"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 9092
  configuration:
    KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
    KAFKA_ZOOKEEPER_CONNECT: "bn-kafka-zookeeper:2181"
    KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.bn-kafka.svc.cluster.local:9092"
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1